apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-workflows-values
  namespace: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  values.yaml: |
    postgresql:
      enabled: false
    server:
      replicaCount: 1
    controller:
      replicaCount: 1
