apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-deployment
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "39.9.0"
    helm:
      releaseName: prometheus
      value: |
        nameOverride: "prometheus-test"
        prometheus:
          service:
            annotations:
              testAnnotation: "test"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
