---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "8.2.0"
    helm:
      releaseName: grafana
      values: |
        nameOverride: "grafana-dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
