apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-deployment
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "8.2.0"
    helm:
      releaseName: grafana
      values: |
        nameOverride: "grafana-prod"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true
