apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
