apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-workflows
      version: "2.3.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: argo-workflows-values
    valuesKey: values.yaml
